variables:
  AWS_REGISTRY: 411720925788.dkr.ecr.us-east-1.amazonaws.com
  AWS_REGION: us-east-1
  AWS_EB_PLATFORM: "arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on 64bit Amazon Linux 2/3.5.3"
  IMAGE_NAME: $AWS_REGISTRY/pietra-marketplace
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

stages:
  - build
  - staging
  - production

.build:
  stage: build
  interruptible: true
  services:
    - docker:dind
  image: docker
  before_script:
    - docker pull amazon/aws-cli -q
    - >
      docker run --rm
      -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      amazon/aws-cli ecr get-login-password --region us-east-1
      | docker login -u AWS --password-stdin $AWS_REGISTRY
  script:
    - docker pull -q $IMAGE_NAME:latest || true
    - >
      docker build
      --cache-from $IMAGE_NAME:latest
      --tag $IMAGE_NAME:$IMAGE_TAG
      --tag $IMAGE_NAME:latest
      .
    - docker push -qa $IMAGE_NAME
  only:
    - master
    - /^v.+$/
  tags:
    - docker

.deploy:
  image: coxauto/aws-ebcli
  before_script:
    - echo IMAGE_NAME_TAG=$IMAGE_NAME:$IMAGE_TAG >> .env
    - echo APP_ENV=$APP_ENV >> .env
  script:
    - eb init pietra-marketplace -r $AWS_REGION -p "$AWS_EB_PLATFORM"
    - eb use $AWS_EB_ENV
    - eb deploy --timeout 30
  #    - curl -sSLf -o /dev/null --retry 3 --retry-connrefused --retry-delay 30 $CI_ENVIRONMENT_URL
  tags:
    - docker

build:
  extends: .build

deploy:staging:
  extends: .deploy
  stage: staging
  needs:
    - build
  variables:
    APP_ENV: staging
    AWS_EB_ENV: pietramarketplace-staging-env
  only:
    - master
  environment:
    name: staging
    url: https://marketplace-staging.pietrastudio.com/

deploy:production:
  extends: .deploy
  stage: production
  needs:
    - build
  variables:
    APP_ENV: production
    AWS_EB_ENV: pietramarketplace-prod-env
  only:
    - /^v.+$/
  environment:
    name: production
    url: https://marketplace.pietrastudio.com/
  when: manual
