version: '3'

services:
  marketplace:
    image: ${IMAGE_NAME_TAG:-pietra-marketplace}
    ports:
      - '80:3000'
    restart: always
    environment:
      - NEXT_APP_ENV
      - NEXT_APP_API_HOST