version: '3'

services:
  marketplace:
    image: ${IMAGE_NAME_TAG:-next-antd}
    ports:
      - '80:3000'
    restart: always
    environment:
      - NEXT_APP_ENV
      - NEXT_APP_API_HOST
      - NEXT_PUBLIC_SENTRY_DSN